### ISSUE TITLE
Add/Remove finalizers on the BucketAccess

### ISSUE THREAD

**Issue by rrati** [kubernetes-sigs/container-object-storage-interface-provisioner-sidecar#18]
The sidecar needs to manage a finalizer on the BucketAccess to ensure that the credential in the backend is deleted before the BucketAccess object is deleted from kubernetes.  The sidecar will need to add a finalizer to the BucketAccess once a credential has been created in the backend.  The central controller will set an annotation on the BucketAccess if the controller is deleting the BucketAccess.  The sidecar needs to check in the update event whether the annotation is set, and if set ensure a safe deletion.  If the annotation is not set then the sidecar needs to do a forced removal of the credential.

Safe delete:
- Verify annotation is set on the BucketAccess
- Wait for all pod finalizers to be removed
- Delete the backend credential
- Once the deletion is successful remove the finalizer on the BucketAccess

Forced delete:
- Verify the annotation on the BucketAccess is not set
- Remove all pod finalizers on the BucketAccess
- Delete the backend credential
- Once the deletion is successful remove the finalizer on the BucketAccess

**Comment by jeffvance** [comment]
_The central controller will set an annotation on the BucketAccess if the controller is deleting the BucketAccess. The sidecar needs to check in the update event whether the annotation is set, and if set ensure a safe deletion. If the annotation is not set then the sidecar needs to do a forced removal of the credential._

@rrati Why is an annotation needed for the sidecar to detect BA deletion? Won't the BA.deletionTimestamp work for this purpose?

**Comment by jeffvance** [comment]
If we believe that COSI must wait [1] for bucket credentials to be revoked/removed when the BAR is deleted then would the same thinking apply to greenfield buckets? IOW, when a BR is deleted should COSI wait [2] until the backend has deleted the bucket?

[1] or if not wait then at least verify that the driver had a chance to delete creds
[2] or if not wait then verify that the greenfield bucket is not available

**Comment by rrati** [comment]
> _The central controller will set an annotation on the BucketAccess if the controller is deleting the BucketAccess. The sidecar needs to check in the update event whether the annotation is set, and if set ensure a safe deletion. If the annotation is not set then the sidecar needs to do a forced removal of the credential._
> 
> @rrati Why is an annotation needed for the sidecar to detect BA deletion? Won't the BA.deletionTimestamp work for this purpose?

The intention for the annotation is to know if the deletion event is graceful (user deleted the BAR) or forceful (admin deletes the BA).  On a graceful deletion we want to wait until the creds are removed from the backend before deleting the BA.  This allows us to give insight to an admin any credentials that may still be granted in the cloud provider.  If a BA exists in the system then there is creds still in the cloud provider.

That is the thought anyway.

**Comment by rrati** [comment]
> If we believe that COSI must wait [1] for bucket credentials to be revoked/removed when the BAR is deleted then would the same thinking apply to greenfield buckets? IOW, when a BR is deleted should COSI wait [2] until the backend has deleted the bucket?
> 
> I ask because I think the KEP is unclear on the separation of COSI and the backend. One _could_ argue that COSI is only responsible for invoking the driver for bucket create, bucket delete, bucket grant, and bucket revoke, but has no responsibility to verify the backend's work. With this view, I believe all COSI needs to do is cause the appropriate driver gRPC to be invoked and handle timeout retries. On the other hand, if COSI is expected to verify backend transactions then it needs a tighter integration with the drivers.
> 
> Thoughts?
> 
> [1] or if not wait then at least verify that the driver had a chance to delete creds
> [2] or if not wait then at least verify that the greenfield bucket is not available

IMO, yes the B should not be deleted in the greenfield case unless the driver has responded that the bucket was successfully deleted.  This would line up with the idea that the B and BAs in the cluster mirror what is in the cloud provider.  I don't think we have actually discussed this case yet though.
