### ISSUE TITLE
Add Deployment documentation

### ISSUE THREAD

**Issue by wlan0** [kubernetes-sigs/container-object-storage-interface-provisioner-sidecar#32]
Now that kustomize files have been added to the root of the project, we need a getting started guide which explains how to deploy and concerns around it. The deployment step itself is a single command now:

```
  kubectl create -k github.com/kubernetes-sigs/container-object-storage-provisioner-sidecar
```

**Comment by krishchow** [comment]
Semi-related, we need documentation or deployment instructions for creating an instance of Minio for the sample-driver as well

**Comment by YiannisGkoufas** [comment]
Totally agree @krishchow I have done some work on that, but I am wondering what is the best place to host that set of instructions. under cmd/sample-driver or in another repo maybe?

**Comment by krishchow** [comment]
I think we want to keep everything related to the sample-driver in this repository right now. so I would say within the main README should be fine for now
