### ISSUE TITLE
Inconsistency on the images name and the deployment yamls

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-sigs/container-object-storage-interface-provisioner-sidecar#48]
# Enhancement

**Is your feature request related to a problem?/Why is this needed**
Not really an important problem. Just an effort to make the whole development process more consistent.
When building the images (by invoking `make container`) the produced images are:
```
objectstorage-sidecar
sample-driver
```
While on the yamls the images used are:
```
objectstorage-sidecar
objectstorage-sample-driver
```

**Describe the solution you'd like in detail**

Just need to implement the convention to rename every component with the `objectstorage-` prefix

**Comment by tparikh** [comment]
@YiannisGkoufas https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/46 Will resolve the issue.
