### ISSUE TITLE
Implement GrantAccess for Minio Provisioner

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes-sigs/container-object-storage-interface-provisioner-sidecar#51]
The current implementation of the sample Minio provisioner needs also the GrantAccess implementation

**Comment by krishchow** [comment]
/close

In one of the more recent community meetings, we discussed the next steps after the minio license change to AGPL. We ended up deciding on a few changes, which included archiving the cosi-driver-minio repository. Instead, we will opt to create a "fake" driver, feel free to reach out on Slack with any questions :)
