### ISSUE TITLE
[Apr-29] - Missing kustomization.yaml and errors when deploying provisioner sidecar

### ISSUE THREAD

**Issue by sdeoras** [kubernetes-sigs/container-object-storage-interface-provisioner-sidecar#56]
# Bug Report

**What happened**:
Hi, I am running into errors when deploying using quick start linked below:
https://github.com/kubernetes-sigs/container-object-storage-interface-api/blob/master/docs/deployment-guide.md#quick-start

In particular, the CRD and the controller deployment went fine, however, provisioner sidecar deployment had following errors:
```
└─ $ ▶ kubectl create -k github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar
error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/private/var/folders/5g/2hsd6d41441dqz17w1yy5llh0000gn/T/kustomize-688061678'
```

**What you expected to happen**:
Expecting to deploy various COSI components without errors

**How to reproduce this bug (as minimally and precisely as possible)**:
Deploy using quick steps and it should error out as mentioned above due to missing `kustomization.yaml` file

**Anything else relevant for this bug report?**:

**Environment**:

- Kubernetes version (use `kubectl version`), please list client and server:
```
└─ $ ▶ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.16-gke.502", GitCommit:"a2a88ab32201dca596d0cdb116bbba3f765ebd36", GitTreeState:"clean", BuildDate:"2021-03-08T22:06:24Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.21) and server (1.18) exceeds the supported minor version skew of +/-1
```
- Sidecar version (provide the release tag or commit hash):
e6139cde3568c46c60d6c8d8bc371e21ba10a153
- Provisoner name and version (provide the release tag or commit hash):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by krishchow** [comment]
For the time being, you can take a look at the https://github.com/kubernetes-sigs/cosi-driver-minio repository. This has a sample kustomization.yaml file for deploying the sidecar with a vendor driver. We removed the customization from this repository since there was no valid deployment of the sidecar without a vendor driver.

**Comment by sdeoras** [comment]
thanks @krishchow let me try that.
