### ISSUE TITLE
Endpoint and region are not being retrieved from credentials.

### ISSUE THREAD

**Issue by Pranaynutanix** [kubernetes-sigs/container-object-storage-interface-provisioner-sidecar#76]
https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/blob/655cc7608237599c010c0f4da936a23974190b55/pkg/bucketaccess/bucketaccess_controller.go#L207

Could we change endpoint and region to be retrieved from credentials just like accessKeys and secretKeys ?

**Comment by thotz** [comment]
Got fixed by https://github.com/kubernetes-sigs/container-object-storage-interface-provisioner-sidecar/pull/77
